name: 'banxe_emi'
version: '1.0.0'
config-version: 2

profile: 'banxe_emi'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  banxe_emi:
    staging:
      +materialized: view
      +schema: staging
    marts:
      safeguarding:
        +materialized: table
        +schema: marts_safeguarding
      fin060:
        +materialized: table
        +schema: marts_fin060
