"""TokenManagerPort — hexagonal port for token lifecycle."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol


class TokenManagerPort(Protocol):
    def issue_access_token(self, customer_id: str) -> tuple[str, datetime]: ...
    def issue_refresh_token(self, customer_id: str) -> tuple[str, datetime]: ...
    def validate_access_token(self, token: str) -> dict: ...
    def validate_refresh_token(self, token: str) -> dict: ...
    def is_inactive(self, last_activity: datetime) -> bool: ...
    def rotate(self, refresh_token: str) -> tuple[str, str, datetime, datetime]: ...
