#!/usr/bin/env python3
"""scip_manifest.py — enumerate SCIP index targets for banxe-emi-stack (STEP3).

Fable 5 rollout STEP3 (docs/canon/GITNEXUS-STEP3-SCIP-INDEX.md). Detects index
targets deterministically from real manifests on disk and joins them to STEP2
ownership zones (config/gitnexus/ownership.map.json, join key = zone name).
The committed target list config/gitnexus/scip.targets.json is a build artifact
of THIS script — never hand-edit both (same contract as CODEOWNERS in STEP2).

Detection rules (deterministic, sorted):
  * python target: repo root if ./pyproject.toml exists; every services/*/pyproject.toml.
  * typescript target: each of apps/*, frontend, external/* that has BOTH
    tsconfig.json AND package.json. A dir with package.json but no tsconfig.json is
    recorded under `excluded` with the reason (NO-MOCK: exclusions are visible,
    never silent).

Usage:
    python3 scripts/gitnexus/scip_manifest.py            # (re)write scip.targets.json
    python3 scripts/gitnexus/scip_manifest.py --check    # exit 1 on drift (CI mode)
    python3 scripts/gitnexus/scip_manifest.py --matrix   # GitHub Actions matrix JSON

stdlib-only, no network. Exit codes: 0 OK · 1 drift (--check).
"""

from __future__ import annotations

import json
from pathlib import Path
import sys

REPO_ROOT = Path(__file__).resolve().parents[2]
MAP_PATH = REPO_ROOT / "config" / "gitnexus" / "ownership.map.json"
OUT_PATH = REPO_ROOT / "config" / "gitnexus" / "scip.targets.json"


def _slug(path: str) -> str:
    """Deterministic artifact slug for a target path."""
    return "root-python" if path == "." else path.replace("/", "-")


def _zones_for(path: str, zones: list[dict]) -> list[str]:
    """Join a target path to STEP2 zone names (only zones with scip_index true).

    Root python target covers every scip-indexed backend zone; a nested target
    covers zones whose patterns live under it; TS targets map to zones whose
    patterns contain the target dir.
    """
    covered: list[str] = []
    for zone in zones:
        if not zone.get("scip_index", False):
            continue
        patterns = [p.strip("/") for p in zone["patterns"]]
        if path == ".":
            # repo-wide python index: backend zones only (frontend has its own targets)
            if zone["zone"] != "frontend":
                covered.append(zone["zone"])
        elif any(p.startswith(path) or path.startswith(p) for p in patterns):
            covered.append(zone["zone"])
    return covered


def detect() -> dict:
    """Scan the tree and build the target manifest (deterministic order)."""
    data = json.loads(MAP_PATH.read_text(encoding="utf-8"))
    zones = data["zones"]

    targets: list[dict] = []
    excluded: list[dict] = []

    if (REPO_ROOT / "pyproject.toml").exists():
        targets.append(
            {"slug": _slug("."), "path": ".", "lang": "python", "zones": _zones_for(".", zones)}
        )
    for manifest in sorted(REPO_ROOT.glob("services/*/pyproject.toml")):
        rel = str(manifest.parent.relative_to(REPO_ROOT))
        targets.append(
            {"slug": _slug(rel), "path": rel, "lang": "python", "zones": _zones_for(rel, zones)}
        )

    ts_candidates = sorted(
        [p for p in (REPO_ROOT / "apps").glob("*") if p.is_dir()]
        + [REPO_ROOT / "frontend"]
        + [p for p in (REPO_ROOT / "external").glob("*") if p.is_dir()]
    )
    for cand in ts_candidates:
        rel = str(cand.relative_to(REPO_ROOT))
        has_pkg = (cand / "package.json").exists()
        has_tsc = (cand / "tsconfig.json").exists()
        if has_pkg and has_tsc:
            targets.append(
                {
                    "slug": _slug(rel),
                    "path": rel,
                    "lang": "typescript",
                    "zones": _zones_for(rel, zones),
                }
            )
        elif has_pkg:
            excluded.append(
                {"path": rel, "reason": "no tsconfig.json (scip-typescript requires one)"}
            )

    return {
        "$schema_note": "GENERATED by scripts/gitnexus/scip_manifest.py — do not hand-edit. "
        "STEP3 SCIP target manifest; zones join to ownership.map.json.",
        "schema_version": "1.0",
        "indexers": data.get("scip", {}).get("indexers", {}),
        "targets": targets,
        "excluded": excluded,
    }


def main(argv: list[str]) -> int:
    """Generate, drift-check, or emit the CI matrix for the SCIP target manifest."""
    manifest = detect()
    rendered = json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"
    if "--matrix" in argv:
        include = [
            {"slug": t["slug"], "path": t["path"], "lang": t["lang"]} for t in manifest["targets"]
        ]
        print(json.dumps({"include": include}))
        return 0
    if "--check" in argv:
        current = OUT_PATH.read_text(encoding="utf-8") if OUT_PATH.exists() else ""
        if current != rendered:
            sys.stderr.write(
                "DRIFT: config/gitnexus/scip.targets.json does not match detection.\n"
                "Regenerate: python3 scripts/gitnexus/scip_manifest.py\n"
            )
            return 1
        print(
            f"scip manifest drift check OK ({len(manifest['targets'])} targets, "
            f"{len(manifest['excluded'])} excluded)"
        )
        return 0
    OUT_PATH.write_text(rendered, encoding="utf-8")
    print(
        f"wrote {OUT_PATH.relative_to(REPO_ROOT)}: {len(manifest['targets'])} targets "
        f"({sum(1 for t in manifest['targets'] if t['lang'] == 'python')} py / "
        f"{sum(1 for t in manifest['targets'] if t['lang'] == 'typescript')} ts), "
        f"{len(manifest['excluded'])} excluded"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
