"""
sendgrid_otp_adapter.py — Production OTP delivery via SendGrid Mail Send API.

Implements OtpDeliveryPort.send_otp via POST /v3/mail/send.
sandbox_mode.enable=True (default) — requests accepted, no mail delivered, no credit consumed.
verify_otp, generate_otp, can_resend are inherited from LegacyOtpAdapter (in-memory).

Env vars:
  SENDGRID_API_KEY    — SendGrid API key (SG....)
  SENDGRID_FROM_EMAIL — Verified sender email address

Only supports channel='email'. Raises ValueError for channel='sms'.

Canon: ADR-029 + ADR-025 §15-16 + OtpDeliveryPort FROZEN (PORT-CONTRACTS-FREEZE-2026-05-08)
"""

from __future__ import annotations

from datetime import UTC, datetime
import logging
import os
from typing import Literal

import httpx

from services.auth.legacy.legacy_otp_adapter import LegacyOtpAdapter
from services.auth.otp_delivery_port import OtpDeliveryReceipt

logger = logging.getLogger(__name__)

_SENDGRID_BASE = "https://api.sendgrid.com"


class SendGridOtpAdapter(LegacyOtpAdapter):
    """
    Production OTP adapter: email delivery via SendGrid Mail Send API.

    send_otp  → POST /v3/mail/send (sandbox_mode.enable=self._sandbox)
    verify_otp, generate_otp, can_resend — inherited in-memory implementation.

    Verification remains in-process because SendGrid is delivery-only.
    The code must be generated by the caller (via generate_otp) and stored
    in-memory (via the parent send_otp call) for subsequent verify_otp.
    """

    def __init__(self, *, sandbox: bool = True) -> None:
        super().__init__()
        self._api_key = os.environ["SENDGRID_API_KEY"]
        self._from_email = os.environ["SENDGRID_FROM_EMAIL"]
        self._sandbox = sandbox
        self._http = httpx.Client(
            base_url=_SENDGRID_BASE,
            headers={"Authorization": f"Bearer {self._api_key}"},
            timeout=10.0,
        )

    # ── OtpDeliveryPort override ──────────────────────────────────────────────

    def send_otp(
        self,
        *,
        channel: Literal["sms", "email"],
        target: str,
        code: str,
        ttl_seconds: int,
    ) -> OtpDeliveryReceipt:
        """
        Send OTP via SendGrid Mail Send API.

        Raises ValueError for channel='sms' — SendGrid is email-only.
        With sandbox=True (default): mail_settings.sandbox_mode.enable=true,
        so no real email is dispatched and no SendGrid credit is consumed.
        """
        if channel != "email":
            raise ValueError(
                f"SendGridOtpAdapter supports only channel='email', got {channel!r}. "
                "Use TwilioOtpAdapter for SMS delivery."
            )
        payload: dict[str, object] = {
            "personalizations": [{"to": [{"email": target}]}],
            "from": {"email": self._from_email},
            "subject": "Your one-time password",
            "content": [
                {
                    "type": "text/plain",
                    "value": f"Your OTP is: {code}\n\nThis code expires in {ttl_seconds} seconds.",
                }
            ],
            "mail_settings": {"sandbox_mode": {"enable": self._sandbox}},
        }
        resp = self._http.post("/v3/mail/send", json=payload)
        resp.raise_for_status()
        now = datetime.now(UTC)
        # mirror into in-memory store so verify_otp (parent) can check
        receipt = super().send_otp(
            channel=channel, target=target, code=code, ttl_seconds=ttl_seconds
        )
        logger.info(
            "SendGrid OTP sent — target=%s sandbox=%s delivery_id=%s",
            target,
            self._sandbox,
            receipt.delivery_id,
        )
        return receipt

    def close(self) -> None:
        self._http.close()

    def __enter__(self) -> SendGridOtpAdapter:
        return self

    def __exit__(self, *_: object) -> None:
        self.close()
