"""
services/design_pipeline/orchestrator.py — AI Design-to-Code Orchestrator
IL-D2C-01 | BANXE EMI AI Bank

Bridges Penpot MCP context with AI code generation.

Pipeline:
  1. Fetch design context from Penpot (component + tokens)
  2. Build structured LLM prompt
  3. LLM generates Mitosis JSX
  4. Compile via Mitosis to target framework
  5. Visual QA screenshot comparison

LLM: Ollama via LangChain (local, qwen2.5-coder:7b by default).
No float for financial values that might appear in UI forms.

FCA/EU AI Act Art.52: AI-generated UI code must be transparently labelled.
"""

from __future__ import annotations

import logging
import time
from typing import Any, Protocol

from services.design_pipeline.models import (
    DesignTokenSet,
    Framework,
    GenerationResult,
    TokenSyncResult,
    VisualQAResult,
)
from services.design_pipeline.penpot_client import PenpotPort
from services.design_pipeline.token_extractor import TokenExtractor

logger = logging.getLogger("banxe.design_pipeline.orchestrator")

_BANXE_AI_DISCLOSURE = (
    "// AI-GENERATED — BANXE Design Pipeline (IL-D2C-01)\n"
    "// EU AI Act Art.52: This code was generated by an AI system.\n"
    "// Review required before production deployment.\n\n"
)


# ── LLM Port ─────────────────────────────────────────────────────────────────


class LLMPort(Protocol):
    """Hexagonal port for any LLM backend (Ollama, OpenAI, Anthropic)."""

    async def agenerate(self, prompt: str) -> str: ...

    @property
    def model_name(self) -> str: ...


# ── Code Generator Port ───────────────────────────────────────────────────────


class CodeGeneratorPort(Protocol):
    """Hexagonal port for the Mitosis / direct code generator."""

    def compile(self, mitosis_jsx: str, framework: Framework) -> str: ...

    def supported_frameworks(self) -> list[Framework]: ...


# ── Visual QA Port ────────────────────────────────────────────────────────────


class VisualQAPort(Protocol):
    """Hexagonal port for visual comparison backend."""

    async def compare(
        self,
        component_id: str,
        rendered_html: str,
        reference_svg: str,
        threshold: float,
    ) -> VisualQAResult: ...


# ── Ollama LLM adapter ────────────────────────────────────────────────────────


class OllamaLLM:
    """
    LLM adapter for Ollama (local inference).

    Falls back gracefully when Ollama is unavailable (returns template scaffold).
    """

    def __init__(
        self,
        base_url: str = "http://localhost:11434",
        model: str = "qwen2.5-coder:7b",
        temperature: float = 0.2,
    ) -> None:
        self._base_url = base_url
        self._model = model
        self._temperature = temperature

    @property
    def model_name(self) -> str:
        return self._model

    async def agenerate(self, prompt: str) -> str:
        try:
            import httpx

            payload = {
                "model": self._model,
                "prompt": prompt,
                "options": {"temperature": self._temperature},
                "stream": False,
            }
            async with httpx.AsyncClient(base_url=self._base_url, timeout=120.0) as client:
                r = await client.post("/api/generate", json=payload)
                r.raise_for_status()
                return r.json().get("response", "")
        except Exception as exc:
            logger.warning("Ollama unavailable (%s) — returning scaffold", exc)
            return self._fallback_scaffold(prompt)

    @staticmethod
    def _fallback_scaffold(prompt: str) -> str:
        """Return a minimal Mitosis JSX scaffold when LLM is unavailable."""
        return (
            "import { useState } from '@builder.io/mitosis';\n\n"
            "export default function GeneratedComponent() {\n"
            "  return (\n"
            '    <div class="banxe-component">\n'
            "      {/* TODO: implement based on design */}\n"
            "    </div>\n"
            "  );\n"
            "}\n"
        )


# ── InMemory LLM (test double) ────────────────────────────────────────────────


class InMemoryLLM:
    """Test double — deterministic response, no network."""

    def __init__(self, response: str = "") -> None:
        self._response = response or (
            "import { useState } from '@builder.io/mitosis';\n\n"
            "export default function TestComponent() {\n"
            '  return <div class="test-component">Test</div>;\n'
            "}\n"
        )
        self._model = "in-memory-mock"

    @property
    def model_name(self) -> str:
        return self._model

    async def agenerate(self, prompt: str) -> str:  # noqa: ARG002
        return self._response


# ── Orchestrator ──────────────────────────────────────────────────────────────


class DesignToCodeOrchestrator:
    """
    AI-powered design-to-code pipeline.

    Composes PenpotPort + LLMPort + CodeGeneratorPort + VisualQAPort
    using dependency injection — all adapters are swappable.

    Args:
        penpot_client:    Any implementation of PenpotPort
        llm:              Any implementation of LLMPort
        code_generator:   Any implementation of CodeGeneratorPort
        visual_qa:        Optional visual QA backend
        token_extractor:  Optional token extractor (for sync_tokens)
    """

    def __init__(
        self,
        penpot_client: PenpotPort,
        llm: LLMPort,
        code_generator: CodeGeneratorPort,
        visual_qa: VisualQAPort | None = None,
        token_extractor: TokenExtractor | None = None,
    ) -> None:
        self._penpot = penpot_client
        self._llm = llm
        self._generator = code_generator
        self._visual_qa = visual_qa
        self._token_extractor = token_extractor or TokenExtractor(penpot_client)

    # ── Public API ────────────────────────────────────────────────────────────

    async def generate_component(
        self,
        file_id: str,
        component_id: str,
        framework: Framework = Framework.REACT,
        run_visual_qa: bool = True,
    ) -> GenerationResult:
        """
        Full pipeline: design context → LLM → compiled code → visual QA.

        Args:
            file_id:       Penpot file UUID
            component_id:  Penpot component UUID
            framework:     Target framework (react, vue, react-native, ...)
            run_visual_qa: Whether to run screenshot comparison

        Returns:
            GenerationResult with compiled code, QA result, and telemetry.
        """
        start_ms = int(time.monotonic() * 1000)
        logger.info("Generating %s for component_id=%s", framework.value, component_id)

        # 1. Get design context from Penpot
        context = await self._penpot.get_component_context(component_id)

        # 2. Get design tokens
        token_set = await self._penpot.get_design_tokens(file_id)

        # 3. Build LLM prompt
        prompt = self._build_prompt(context, token_set, framework)

        # 4. LLM generates Mitosis JSX
        mitosis_jsx = await self._llm.agenerate(prompt)

        # 5. Compile via Mitosis/direct to target framework
        compiled_code = self._generator.compile(mitosis_jsx, framework)

        # 6. Add AI disclosure header (EU AI Act Art.52)
        final_code = _BANXE_AI_DISCLOSURE + compiled_code

        # 7. Visual QA (optional)
        qa_result: VisualQAResult | None = None
        if run_visual_qa and self._visual_qa is not None:
            reference_svg = await self._penpot.get_component_svg(file_id, component_id)
            qa_result = await self._visual_qa.compare(
                component_id=component_id,
                rendered_html=final_code,
                reference_svg=reference_svg,
                threshold=0.95,
            )
            if not qa_result.passed:
                logger.warning(
                    "Visual QA failed for component_id=%s: similarity=%.3f",
                    component_id,
                    qa_result.similarity_score,
                )

        latency_ms = int(time.monotonic() * 1000) - start_ms
        return GenerationResult(
            component_id=component_id,
            framework=framework,
            code=final_code,
            mitosis_jsx=mitosis_jsx,
            qa_result=qa_result,
            latency_ms=latency_ms,
            model_used=self._llm.model_name,
        )

    async def generate_page(
        self,
        file_id: str,
        page_id: str,
        framework: Framework = Framework.REACT,
    ) -> list[GenerationResult]:
        """
        Generate code for all components on a Penpot page.

        Fetches page structure, breaks into components, generates each,
        and returns the full list of GenerationResult objects.
        """
        page = await self._penpot.get_page_structure(file_id, page_id)
        components = page.components or await self._penpot.get_file_components(file_id)

        results = []
        for component in components:
            result = await self.generate_component(
                file_id=file_id,
                component_id=component.id,
                framework=framework,
                run_visual_qa=False,  # Skip QA in batch mode
            )
            results.append(result)

        logger.info("Generated %d components for page_id=%s", len(results), page_id)
        return results

    async def sync_tokens(self, file_id: str) -> TokenSyncResult:
        """
        Sync design tokens: Penpot → banxe-tokens.json → Style Dictionary outputs.
        """
        logger.info("Syncing design tokens from file_id=%s", file_id)
        return await self._token_extractor.sync(file_id)

    # ── Prompt builder ────────────────────────────────────────────────────────

    @staticmethod
    def _build_prompt(
        context: dict[str, Any],
        tokens: DesignTokenSet,
        framework: Framework,
    ) -> str:
        """Build a structured prompt for the code generation LLM."""
        token_summary = _format_tokens_for_prompt(tokens)
        context_json = _safe_json_truncate(context, max_chars=3000)

        return f"""You are an expert {framework.value} developer building UI components for BANXE AI Bank.

DESIGN CONTEXT (from Penpot):
{context_json}

DESIGN TOKENS (use these for all styling):
{token_summary}

TASK:
Generate a {framework.value} component using Mitosis JSX syntax.

REQUIREMENTS:
1. Use only the design tokens listed above for colours, spacing, and typography
2. Output valid Mitosis JSX that compiles to {framework.value}
3. Use CSS classes following BEM naming: banxe-<component>__<element>--<modifier>
4. GDPR: do NOT log, store, or transmit any PII from form fields
5. Accessibility: include aria-label, role, and tabIndex where appropriate
6. Add a comment: // BANXE Design Pipeline (IL-D2C-01)

OUTPUT: Only the Mitosis JSX component code. No explanations.
"""

    # ── Telemetry helper ──────────────────────────────────────────────────────

    async def emit_metrics(self, result: GenerationResult, agent_type: str) -> None:
        """
        Emit generation metrics to ClickHouse for Grafana dashboard.

        Non-critical — errors are logged but not raised.
        """
        from decimal import Decimal

        from services.design_pipeline.models import DesignPipelineMetrics

        metrics = DesignPipelineMetrics(
            component_id=result.component_id,
            framework=result.framework.value,
            tokens_used=result.tokens_used,
            latency_ms=result.latency_ms,
            qa_similarity=result.qa_result.similarity_score if result.qa_result else 0.0,
            qa_passed=result.qa_passed,
            model_used=result.model_used,
            agent_type=agent_type,
            cost_usd=Decimal("0"),  # Ollama is free, cost only for cloud LLMs
        )
        logger.debug("Pipeline metrics: %s", metrics.to_clickhouse_dict())


# ── Utilities ─────────────────────────────────────────────────────────────────


def _format_tokens_for_prompt(tokens: DesignTokenSet) -> str:
    lines = []
    if tokens.colors:
        lines.append("Colors:")
        for c in tokens.colors[:10]:
            lines.append(f"  {c.name}: {c.value}")
    if tokens.spacing:
        lines.append("Spacing:")
        for s in tokens.spacing[:8]:
            lines.append(f"  {s.name}: {s.value}")
    if tokens.typography:
        lines.append("Typography:")
        for t in tokens.typography[:5]:
            lines.append(f"  {t.name}: {t.font_size} / {t.font_weight}")
    return "\n".join(lines) or "No tokens available"


def _safe_json_truncate(data: dict[str, Any], max_chars: int = 3000) -> str:
    import json

    raw = json.dumps(data, indent=2)
    if len(raw) <= max_chars:
        return raw
    return raw[:max_chars] + "\n... [truncated]"
